{
 "title": "Apple health specific metrics",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "show tag values from \"data-sources\" with key=device"
   }
  ]
 },
 "panels": [
  { "title": "Yearly Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cycled distance this year ($tag_unit)",
     "measurement": "BodyMass",
     "query": "SELECT sum(\"value\") FROM \"DistanceCycling\" WHERE (\"device\" =~ /^$source$/) AND  time > now() - 365d GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Distance swam this year (km)",
     "measurement": "DistanceSwimming",
     "query": "SELECT sum(\"value\")/1000 FROM \"DistanceSwimming\" WHERE (\"device\" =~ /^$source$/) AND  time > now() - 365d GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Walked/ran distance this year ($tag_unit)",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\") FROM \"DistanceWalkingRunning\" WHERE (\"device\" =~ /^$source$/) AND  time > now() - 365d GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Flights climbed this year ($tag_unit)",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\") FROM \"FlightsClimbed\" WHERE (\"device\" =~ /^$source$/) AND  time > now() - 365d GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Steps this year ($tag_unit)",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\") FROM \"StepCount\" WHERE (\"device\" =~ /^$source$/) AND  time > now() - 365d GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Hours exercising (hours)",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\")/60 FROM \"AppleExerciseTime\" WHERE (\"device\" =~ /^$source$/) AND  time > now() - 365d GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Hours standing up year (hours)",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\")/60 FROM \"AppleStandTime\" WHERE (\"device\" =~ /^$source$/) AND  time > now() - 365d GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Daily Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Distance walked per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DistanceWalkingRunning",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  },
  {
   "title": "Distance cycled per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "DistanceCycling",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Minutes of exercise per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AppleExerciseTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steps per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "steps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StepCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  },
  {
   "title": "Flights climbed  per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "flights" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FlightsClimbed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy burned per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "alias": "Active Energy",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ActiveEnergyBurned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Basal Energy",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "BasalEnergyBurned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time spent standing up per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AppleStandTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average walking speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "WalkingSpeed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Heart infos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Heart infos (per day)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "Walking heart rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "WalkingHeartRateAverage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Resting heart rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "RestingHeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min/Max heart rate (per day)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "Lowest heart rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "alias": "Highest heart rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart rate variability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRateVariabilitySDNN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of low and high heart rate events per day ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "Low heart rate events",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LowHeartRateEvent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "High heart rate events",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HighHeartRateEvent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart rate through the day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Active time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AppleExerciseTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Sleep data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Times in bed/sleeping",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "device::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepAnalysisTimes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  },
  {
   "title": "Durations of time in bed",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "device::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "SleepAnalysis",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Sleep Goal",
     "measurement": "SleepDurationGoal",
     "query": "SELECT \"value\" FROM \"autogen\".\"SleepDurationGoal\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total time spent in bed ($tag_device)",
     "groupBy": [
      { "params": [ "device::tag" ], "type": "tag" }
     ],
     "measurement": "SleepAnalysis",
     "query": "SELECT sum(\"value\") FROM \"autogen\".\"SleepAnalysis\" WHERE (\"state\"::tag = 'HKCategoryValueSleepAnalysisInBed') AND $timeFilter GROUP BY \"device\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "state::tag",
       "operator": "=",
       "value": "HKCategoryValueSleepAnalysisInBed"
      }
     ]
    },
    {
     "alias": "Total time spent asleep ($tag_device)",
     "groupBy": [
      { "params": [ "device::tag" ], "type": "tag" }
     ],
     "measurement": "SleepAnalysis",
     "query": "SELECT sum(\"value\") FROM \"autogen\".\"SleepAnalysis\" WHERE (\"state\"::tag = 'HKCategoryValueSleepAnalysisInBed') AND $timeFilter GROUP BY \"device\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "state::tag",
       "operator": "=",
       "value": "HKCategoryValueSleepAnalysisAsleepUnspecified"
      }
     ]
    }
   ]
  }
 ]
}